package com.example.domain.model

data class User(
    override val login: String,
    override val id: Long,
    override val name: String,
    val nodeId: String,
    override val avatarUrl: String,
    val gravatarId: String,
    override val url: String,
    val htmlUrl: String,
    val followersUrl: String,
    val followingUrl: String,
    val gistsUrl: String,
    val starredUrl: String,
    val subscriptionsUrl: String,
    val organizationsUrl: String,
    val reposUrl: String,
    val eventsUrl: String,
    val receivedEventsUrl: String,
    val type: String,
    val siteAdmin: Boolean,
    val location: String,
    val company: String,
    val email: String,
    val bio: String,
    val twitterUsername : String,
    val followers : Int,
    val following : Int,
    val createdAt : String
) : UserBaseInfo
